Routing fixes
NASA-PDS/pds-doi-ui pull request #66
Opened 2021-07-07 22:59 UTC by eddiesarevalo

Fixed the issues caused by merging #22 #52 #57 together. The pull requests had to be updated with the router code.
This also adds #65 through #52

resolves #22 
resolves #52 
resolves #57 
resolves #65 

I need @c-suh to verify that the latest changes are there and functional. I tested end to end with a dummy excel doi. @c-suh can use her tests to double check everything is working.

2021-07-08 19:34 UTC, tloubrieu-jpl requested changes
That is a big one, thanks Eddie for putting that together.

Only change I would ask for is the button "Reserve a new DOI" should be "create a new DOI" or "create another DOI" (since we are asking the question again `Has the data been registered and made publicly available?` in the next step, the user can reserve or draft/release a DOI).

Otherwise that sounds good to me. I will wait for @c-suh 's review before I merge.

Thanks,

2021-07-10 02:15 UTC, c-suh commented on src/components/SearchResults.jsx
> +				</div>
Since the majority of this is commented out, this whole chunk could be `null` or its contents deleted.

2021-07-10 02:27 UTC, c-suh reviewed
This is looking good, @eddiesarevalo ! I did notice a few things and pushed a change for an overlooked placeholder link.

1. Search behavior: IIRC, the latest decision regarding the default view for the [Search page ](http://localhost:3000/search) is that it's not supposed to display any results until the search button (or enter from the search bar) is entered.
2. Search behavior: clicking the 'X' in the search bar to clear the search - should this clear the results as well as the text in the search bar?
3. There's a chunk of code in SearchResults.jsx (lines 187-279) which is mostly comments. Either the commented out part can be deleted or those lines can be replaced with `null`.

2021-07-10 02:30 UTC, c-suh commented
@tloubrieu-jpl, I left a review [above](https://github.com/NASA-PDS/pds-doi-ui/pull/66#pullrequestreview-703463063), but you might want to sign off on my points 1 and 2 as "fine as is"?

2021-07-12 16:31 UTC, tloubrieu-jpl commented
Thanks @c-suh , I will create new tickets for your comments so that I can merge now. Thanks

2021-07-12 16:41 UTC, tloubrieu-jpl commented
Hi @eddiesarevalo,

Were you able to change the buton label to create a new DOI after one is reserved ?

Thanks,

Thomas

2021-07-12 19:05 UTC, eddiesarevalo commented
@tloubrieu-jpl I changed the label for the button. I also changed the basename subdiretory to '/dois'

2021-07-12 20:18 UTC, tloubrieu-jpl commented
thanks @eddiesarevalo , is the basename subdiretory hardcoded ? 

for the production deployment we want to deploy the build application in an apache directory and ideally the application would be agnostic of which apache directory it is deployed in.

2021-07-13 16:05 UTC, eddiesarevalo commented
@tloubrieu-jpl Try to test this latest commit. It should allow deployment on any sub directory. I have only been able to test locally but you can try it on your server. 

Use `npm run build` to get the built code.

2021-07-13 17:01 UTC, tloubrieu-jpl commented
Thanks @eddiesarevalo that works. There is only a minor issue that does not prevent from merging and deploying on pds-gamma. I created a ticket #70

2021-07-13 17:16 UTC, merged